config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "recipes#index"
  namespace :recipes do
    resources :searches, only: :index
  end
  resources :recipes, only: [:index, :new, :create, :destroy, :edit, :update, :show] do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :show, :destroy]
    resources :reports, only: [:new, :create, :show]
    collection do
      get 'main'
      get 'side'
      get 'soup'
    end
  end

  resources :users, only: [:show] do
    member do
      get :favorites
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  acts_as_taggable

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :materials, foreign_key: "recipe_id", dependent: :destroy
  accepts_nested_attributes_for :materials, allow_destroy: true
  has_many :steps, foreign_key: "recipe_id", dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy

  validates :title, presence: true
  validates :image, presence: true
  validates :calorie, presence: true
  validates :sugar, presence: true
  validates :category, presence: true


end

app/controllers/recipes/searches_controller.rb
class Recipes::SearchesController < ApplicationController
  def index
    redirect_to root_path if params[:keyword] == ""
    split_keyword = params[:keyword].split(/[[:blank:]]+/)
    @recipes = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @recipes += Recipe.joins(:materials).where('recipes.title LIKE (?) AND materials.name LIKE (?)', "%#{keyword}%", "%#{keyword}%")
    end
    @recipes.uniq!
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :move_to_index, except: [:index, :show, :search, :main, :side, :soup]
  def index
    if params[:tag]
      @recipes = Recipe.tagged_with(params[:tag])
    else
      @recipes = Recipe.page(params[:page]).per(4).order("created_at DESC")
    end

    if params[:tag_name]
      @recipes = Recipe.tagged_with("#{params[:tag_name]}").page(params[:page]).per(4)
    end
    # @tags = Recipe.tag_counts_on(:tags).order('count DESC')
    @popular_tags = ActsAsTaggableOn::Tag.most_used(8)   
  end

  def main
    @recipes = Recipe.where(category: "main").page(params[:page]).per(4).order("created_at DESC")
  end

  def side
    @recipes = Recipe.where(category: "side").page(params[:page]).per(4).order("created_at DESC")
  end

  def soup
    @recipes = Recipe.where(category: "soup").page(params[:page]).per(4).order("created_at DESC")
  end

  def new
    @recipe = Recipe.new
    @recipe.materials.build
    @recipe.steps.build
    @all_tag_list = ActsAsTaggableOn::Tag.all.pluck(:name)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path, notice: '投稿が完了しました'
    else
      render :new
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to root_path, notice: '削除が完了しました'
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    recipe = Recipe.find(params[:id])
    if recipe.update(recipe_params)
      redirect_to root_path, notice: '編集が完了しました'
    else
      redirect_to root_path, alert: '編集に失敗しました'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @favorite = Favorite.new
    @favorites_count = Favorite.where(recipe_id: @recipe.id).count
    @comment = Comment.new
    @comments = @recipe.comments.includes(:user)
    @comments_count = Comment.where(recipe_id: @recipe.id).count
    @reports_count = Report.where(recipe_id: @recipe.id).count
  end

  def search
    redirect_to root_path if params[:keyword] == ""
    split_keyword = params[:keyword].split(/[[:blank:]]+/)
    @recipes = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @recipes += Recipe.joins(:materials).where('recipes.title LIKE (?) AND materials.name LIKE (?)', "%#{keyword}%", "%#{keyword}%")
    end
    @recipes.uniq!
    @recipes = Recipe.page(params[:page]).per(4).order("created_at DESC")
  end


  private

  def recipe_params
    params.require(:recipe).permit(:title, :category, :image, :calorie, :sugar, :tag_list,  materials_attributes: [:id, :name, :amount, :_destroy], steps_attributes: [:id, :number, :process, :_destroy]).merge(user_id: current_user.id)
  end

  def update_recipe_params
    params.require(:recipe).permit(:title, :category, :image, :calorie, :sugar, :tag_list, materials_attributes: [:name, :amount, :_destroy, :id], steps_attributes: [:number, :process, :_destroy, :id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/helpers/recipes/searches_helper.rb
module Recipes::SearchesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_favorite.html.erb
<% if current_user.already_favorited?(@recipe) %>
  <%= link_to recipe_favorite_path(@recipe), method: :delete, remote: true do %>
    <i class="fas fa-heart fa-2x"></i>
  <% end %>
<% else %>
  <%= link_to recipe_favorites_path(@recipe), method: :post, remote: true do %>
    <i class="far fa-heart fa-2x"></i>
  <% end %>
<% end %>

app/views/recipes/_form.html.erb
    <%= render 'layouts/error_messages', { target: @recipe } %>
<div class="contents_form">
  <div class="contents_form__val">
  <%= form_for @recipe do |f| %>
    <div class="title-field">
      <%= f.text_field :title , placeholder: "Title" %>
    </div>
    <div class="category-field">
      <label><%= f.radio_button :category, :main%> main </label>
      <label><%= f.radio_button :category, "side"%> side </label>
      <label><%= f.radio_button :category, "soup"%> soup </label>
    </div>
    <div class="img-field">
      <%= f.label :image ,"画像を選択"%>
      <%= f.file_field :image ,class:"img-btn" ,id: :recipe_image %>
    </div>
    <div class="data-field">
      <%= f.text_field :calorie , placeholder: "カロリー",class: "calorie-field"%>
      <%= f.text_field :sugar , placeholder: "糖質",class: "sugar-field"%>
    </div>
    <div class="tag-field">
      <h2>タグ ( カンマで区切ってください )</h2>
    <ul><%= f.text_field :tag_list, value: @recipe.tag_list.join(','), class: "form-control", id: "myTags" %></ul>
    </div>
    <div id="materials" > 
      <h2>材料</h2>
      <%= f.fields_for :materials do |material| %>
        <%= render 'material_fields', f: material %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association '▽ 材料を追加する',f, :materials ,id:"material-add-btn" %>       
      </div>
    </div>

    <div id="steps">
    <h2>手順</h2>
      <%= f.fields_for :steps do |step| %>
        <%= render 'step_fields', f:step %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association '▽ 手順を追加する',f, :steps,id:"step-add-btn" %>
      </div>
    </div>
    <div class="btn-send">
    <%= f.submit "投稿する", class:"send-btn" %>
    </div> 
  <% end %>
  </div>
</div>    

app/views/recipes/_material_fields.html.erb
<div class='nested-fields'>
    <div class="field">
      <%= f.text_field :name, placeholder: "食材" %>
      <%= f.text_field :amount, placeholder: "量" %> 
      <%= link_to_remove_association "削除", f ,id: "material-remove-btn"%>
    </div>
</div>

app/views/recipes/_step_fields.html.erb
<div class='nested-fields'>
    <div class="field">
      <%= f.number_field :number, placeholder: "番号" ,class:"number-field"%>
      <%= f.text_field :process, placeholder: "内容" ,class:"process-field"%> 
      <%= link_to_remove_association "削除", f ,id:"step-remove-btn"%>
    </div>
</div>

app/views/recipes/_tag_list.html.erb
<% @recipe.tag_list.each do |tag| %>
  <%= link_to tag, recipes_path(tag_name: tag),class: "text-white"%>
<% end %>

app/views/recipes/edit.html.erb
<div class="contents_form">
  <%= form_for @recipe do |f| %>
    <div class="title-field">
      <%= f.text_field :title , placeholder: "Title" %>
    </div>
      <div class="preview-content">
        <div class="image-content">            
          <%= image_tag @recipe.image.to_s %>
        </div>
      </div>
    <div class="img-field">
      <%= f.label :image ,"画像を変更する"%>
      <%= f.file_field :image ,class:"img-btn" ,id: :recipe_image %>
    </div> 
    <div class="data-field">
      <%= f.text_field :calorie , placeholder: "カロリー",class: "calorie-field"%>
      <%= f.text_field :sugar , placeholder: "糖質",class: "sugar-field"%>
    </div>
    <div class="tag-field">
      <h2>タグ ( カンマで区切ってください )</h2>
    <ul><%= f.text_field :tag_list, value: @recipe.tag_list.join(','), class: "form-control", id: "myTags" %></ul>
    
    <div id="materials" > 
      <h2>材料</h2>
      <%= f.fields_for :materials do |material| %>
        <%= render 'material_fields', f: material %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association '▽ 材料を追加する',f, :materials ,id:"material-add-btn" %>       
      </div>
    </div>

    <div id="steps">
    <h2>手順</h2>
      <%= f.fields_for :steps do |step| %>
        <%= render 'step_fields', f:step %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association '▽ 手順を追加する',f, :steps,id:"step-add-btn" %>
      </div>
    </div>
    <div class="btn-send">
    <%= f.submit "投稿する", class:"send-btn" %>
    </div> 
  <% end %>
</div>    

app/views/recipes/index.html.erb
  <div class="contents">
    <div class="search-content">
      <%= form_with(url: recipes_searches_path, local: true, method: :get, id: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "検索する", id: "search-input" %>
        <%= button_tag type:"submit", id: "search-btn" do %>
        <i class="fas fa-search fa-2x"></i>
        <% end %>
      <% end %>
    </div>
    <div class="category-content">
      <ul>
        <li class="btn-circle-border", id="main"><%= link_to "main","/recipes/main" %></li>
        <li class="btn-circle-border", id="side"><%= link_to "side","/recipes/side" %></li>
        <li class="btn-circle-border", id="soup"><%= link_to "soup","/recipes/soup" %></li>
      <ul>
    </div>
    <div class="middle-content">
      <div class="ranking">
        <i class="fas fa-crown fa-2x"></i>
        <p>ranking</p>
      </div>
      <% @popular_tags.each do |ptag|%>
        <%= link_to ptag, recipes_path(tag_name: ptag.name) , class: "text-white"%>      
      <% end %>
    </div>
    <div class="under-content">
      <% @recipes.each do |recipe|%>
        <div class="l-wrapper">
          <article class="card">        
            <div class="card__header">
              <h3 class="card__header__title"><%= recipe.title %></h3>
              <figure class="card__header__thumbnail">
                <%= image_tag recipe.image.to_s%>
              </figure>
            </div>
            <div class="card__body">
              <div class="maru">
                <div class="cal"><%= recipe.calorie %>kcal</div>
              </div>
              <div class="maru size_noemal orange">
                <div class="sug"><%= recipe.sugar%>g</div>
              </div>
            </div>
            <div class="card__footer">
            <p class=""><p class="card__footer__text"><%= link_to '詳細をみる', "/recipes/#{recipe.id}", method: :get ,class:"button -compact"%></p>
            </div>
          </article>
        </div>
      <% end %> 
    </div>
      <div class="peginate">       
        <div class='index-paginate'> <%= paginate(@recipes) %></div>
      </div>
  </div>

app/views/recipes/main.html.erb
<div class="contents">
  <div class="under-content">
    <% @recipes.each do |recipe|%>
      <div class="l-wrapper">
        <article class="card">        
          <div class="card__header">
            <h3 class="card__header__title"><%= recipe.title %></h3>
            <figure class="card__header__thumbnail">
              <%= image_tag recipe.image.to_s%>
            </figure>
          </div>
          <div class="card__body">
            <div class="maru">
              <div class="cal"><%= recipe.calorie %>kcal</div>
            </div>
            <div class="maru size_noemal orange">
              <div class="sug"><%= recipe.sugar%>g</div>
            </div>
          </div>
          <div class="card__footer">
            <p class=""><p class="card__footer__text"><%= link_to '詳細をみる', "/recipes/#{recipe.id}", method: :get ,class:"button -compact"%></p>
          </div>
        </article>
      </div>
    <% end %>
  </div>
</div>        

app/views/recipes/new.html.erb
<%= render 'form', recipe: @recipe %> 

app/views/recipes/show.html.erb
<div class="details-content">
  <div class="content_post">
    <div class="content_post__left">
      <% if user_signed_in? %>
        <div id="favorite-<%= @recipe.id %>",class="fav_btn">
          <%= render partial: "favorite", locals: { recipe: @recipe } %>
        </div>
        <div class="content_post__left__fav"><%= @favorites_count %></div>
      <% end %>
      <div class="report">
        <div id="reports">
          <i class="fas fa-utensils fa-2x"></i>
          <%= @reports_count %>
        </div>
        <div class="report__select">
          <div class="report__select__write"><%= link_to "レポを書く",new_recipe_report_path(@recipe) %></div>
          <div class="report__select__see"><%= link_to "レポを見る",recipe_report_path(@recipe)%></div>
        </div>     
      </div>
    </div>
    <% if user_signed_in? && current_user.id == @recipe.user_id %>
      <div class = "more_list">
        <%= link_to "/recipes/#{@recipe.id}/edit", method: :get ,class: "list-btn" do %>
        <i class="fas fa-edit fa-2x "></i>
        <% end %>
        <%= link_to "/recipes/#{@recipe.id}", method: :delete ,class: "list-btn", data: { confirm: '削除しますか？' } do %>
        <i class="far fa-trash-alt fa-2x"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="recipe-content">  
    <div class="recipe-header">   
      <div class="title"><%= @recipe.title %></div>
      <div class="diet">
        <div class="calorie">カロリー<%= @recipe.calorie %>kcal</div>
        <div class="sugar">糖質<%= @recipe.sugar%>g</div>
      </div>
      <div class="tags">
        <span class="tag-list">
        <%= render 'recipes/tag_list', tag_list: @recipe.tag_list %>
        </span>
      </div>
      <div class="user-name">
        <span class="name">
          <a href="/users/<%= @recipe.user.id %>">
            <span><%= @recipe.user.nickname %>さん</span>
          </a>
        </span>
      </div>
    </div>
    <div class="image-material">
      <div class="recipe-img"><%= image_tag @recipe.image.to_s%></div>
      <div class="materials">
        <h2>材料</h2>
      <% @recipe.materials.each do |material| %>
      <ul class="material">
        <li><%= material.name %></li>
        <li><%= material.amount%></li>
      </ul>
      <% end %>
      </div>
    </div>
    <div class="steps">
      <h2>作り方</h2>
      <% @recipe.steps.each do |step| %>
        <ul class = "step">
          <li class="step"><%= step.number %></li>
          <li class="process"><%= step.process%></li>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="comment-content">
    <% if current_user%>
      <div class="comment-content__comments">
        <div id="comments">
        <i class="far fa-comments fa-2x"></i>
        <%= @comments_count %>
        </div>
        <div class="comment-select">
          <div class="comment-select__write">コメントする</div>
          <%= link_to "コメントを見る", recipe_comment_path(@recipe),class:"comment-select__see" %>
        </div>
        <%= form_with(model: [@recipe, @comment], local: true) do |f| %>
        <div class="comment-fields">
          <div class="comment-field">
            <%= f.text_area :text, placeholder: "コメントする", rows: "2" %>
            <%= f.submit "SEND" ,class:"comment-btn"%>
          </div>
        </div>
        <% end %>
    <% else %>
    <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
  <% end %>
      </div>
    </div> 
  </div> 
</div>

app/views/recipes/side.html.erb
<div class="contents">
  <div class="under-content">
    <% @recipes.each do |recipe|%>
      <div class="l-wrapper">
        <article class="card">        
          <div class="card__header">
            <h3 class="card__header__title"><%= recipe.title %></h3>
            <figure class="card__header__thumbnail">
              <%= image_tag recipe.image.to_s%>
            </figure>
          </div>
          <div class="card__body">
            <div class="maru">
              <div class="cal"><%= recipe.calorie %>kcal</div>
            </div>
            <div class="maru size_noemal orange">
              <div class="sug"><%= recipe.sugar%>g</div>
            </div>
          </div>
          <div class="card__footer">
            <p class="card__footer__text"><%= link_to '詳細をみる', "/recipes/#{recipe.id}", method: :get ,class:"button -compact"%></p>
          </div>
        </article>
      </div>
    <% end %>
  </div>
</div>        

app/views/recipes/soup.html.erb
<div class="contents">
  <div class="under-content">
    <% @recipes.each do |recipe|%>
      <div class="l-wrapper">
        <article class="card">        
          <div class="card__header">
            <h3 class="card__header__title"><%= recipe.title %></h3>
            <figure class="card__header__thumbnail">
              <%= image_tag recipe.image.to_s%>
            </figure>
          </div>
          <div class="card__body">
            <div class="maru">
              <div class="cal"><%= recipe.calorie %>kcal</div>
            </div>
            <div class="maru size_noemal orange">
              <div class="sug"><%= recipe.sugar%>g</div>
            </div>
            </div>
          <div class="card__footer">
            <p class=""><p class="card__footer__text"><%= link_to '詳細をみる', "/recipes/#{recipe.id}", method: :get ,class:"button -compact"%></p>
          </div>
        </article>
      </div>
    <% end %>
  </div>
</div>        

app/views/recipes/update.html.erb
<div class="update-contents">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">→ RETURN</a>
  </div>
</div>