config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "recipes#index"
  namespace :recipes do
    resources :searches, only: :index
  end
  resources :recipes, only: [:index, :new, :create, :destroy, :edit, :update, :show] do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :show, :destroy]
    resources :reports, only: [:new, :create, :show]
    collection do
      get 'main'
      get 'side'
      get 'soup'
    end
  end

  resources :users, only: [:show] do
    member do
      get :favorites
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
end

app/views/layouts/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="text-danger" role="alert">
    <h3>エラー項目があります</h3>
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notifications.html.erb
<div class="notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RecipeApp</title>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
  <%= render 'layouts/notifications'%>

  <header id="header">
    <h1 class="logo"><%= link_to "Recipe",root_path %></h1>
    <div class="search-content">
        <%= form_with(url: recipes_searches_path, local: true, method: :get, id: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "検索する", id: "search-input" %>
        <%= button_tag type:"submit", id: "search-btn" do %>
        <i class="fas fa-search fa-2x"></i>
        <% end %>
        <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="dropdwn">
        <li class="btn-flat-border">メニュー
          <ul class="dropdwn__menu">
            <li><%= link_to "マイページ","/users/#{current_user.id}" %></li>
            <li><%= link_to "お気に入り", "/users/#{current_user.id}/favorites"%></li>
            <li><%= link_to "新規投稿", "/recipes/new", class: "post" %></li>
            <li><%= link_to "プロフィール変更", "/users/edit" %></li>
          </ul>
        </li>
      </div>
      <div class="log-out">
        <li class="btn-flat-border"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></div>
      </div>
    <% else %>
      <div class="btn">
        <ul>
          <li class="btn-flat-border"><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
          <li class="btn-flat-border"><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
          <li class="btn-flat-border"><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></li>
        </ul>
      </div>
    <% end %>
    <% if user_signed_in? %>
    <% else %>
      <div class="guest">
        <ul>
          <li class="btn-flat-border"><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
          <li class="btn-flat-border"><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
        </ul>
      </div>
    <% end %>
  </header>
    <%= yield %>
    <% if user_signed_in? %>
    <footer>
      <div class="under-nav">
        <ul class="under-nav__menu">
          <li>
            <%= link_to "/users/#{current_user.id}" do %>
              <i class="fas fa-user-circle fa-2x"><p>マイページ</p></i>
            <% end %>
          </li>
          <li>
            <%= link_to "/users/#{current_user.id}/favorites" do %>
              <i class="fas fa-heart fa-2x"><p>お気に入り</p></i>
            <% end %>
          </li>
          <li>
            <%= link_to "/recipes/new", class: "post" do%>
              <i class="fas fa-pen fa-2x"><p>新規投稿</P></i>
            <% end %>
          </li>
          <li>
          <%= link_to "/users/edit" do %>
            <i class="fas fa-user-edit fa-2x"><p>登録情報変更</p></i>
          <% end %>
          </li>
        </ul>
      </div>
    </footer>
    <% end %>
  </body>
</html>